### ISSUE TITLE
Test HTML produced on server hydrates without errors on client-side

### ISSUE THREAD

**Issue by overlookmotel** [overlookmotel/react-async-ssr#2]
I think it should work fine, but would be good to test.

**Comment by revskill10** [comment]
I got mismatched error when using `hydrate` .
With `render` , there's no mismatched error on client.

**Comment by overlookmotel** [comment]
Can you please post the code that produces this error?

**Comment by revskill10** [comment]
@overlookmotel I setup global state and use it as a `cache` to hydrate later:
```js
const { setGlobal, getGlobal, addReducer, resetGlobal } = require('reactn');
const LRU = require('lru_map').LRUMap
const LIMIT = 10
const setupGlobal = ({cache}) => {    
  setGlobal({
    cache
  });
  addReducer('setCache', (global, key, record) => {
    global.cache.set(key, record)
    return {
      cache: global.cache
    }}
  );

  addReducer('evictCache', (global, key) => {
    //delete(global.cache, key)
    global.cache.delete(key)
    return {
      cache: global.cache
    }}
  );
}

export const setupGlobalCache = (limit = LIMIT) => {
  resetGlobal()
  let cache = new LRU(limit);

  setupGlobal({cache})
}

export const getGlobalCache = () => {
  const cache = getGlobal().cache.toJSON()
  return {
    cache
  }
}

export const loadGlobalCache = (serialized, limit = LIMIT) => {
  resetGlobal()
  const cache = new LRU(serialized)
  window.__CACHE__ = cache
  //cache.fromJSON(serialized.cache)
  setupGlobal({cache})
}
```
Then do serialization on `server.js`
```js
const globalValue = getGlobalCache().cache.map(it => [it.key, it.value])
...
<script id='graphql-state'>
          window.__PRELOADED_STATE__=${serialize({cache:globalValue})}
        </script>
```
Then on `client.js`
```js
import { loadGlobalCache } from './ssr/lru-cache'
loadGlobalCache(window.__PRELOADED_STATE__.cache)
loadableReady(() => {
  const sheetsManager = new Map();
  const generateClassName = createGenerateClassName();
  hydrate(
    <JssProvider generateClassName={generateClassName}>
      <MuiThemeProvider sheetsManager={sheetsManager} theme={theme}>
        <App />
      </MuiThemeProvider>
    </JssProvider>
)
```

**Comment by revskill10** [comment]
I think, because `render` has no warning, mean that something is wrong with client-side suspending when using with `hydrating` , so server-side or state part is not the problem here ?

**Comment by overlookmotel** [comment]
@revskill10 There's a lot of moving parts here. Are you able to simplify it?

I can't really investigate this as I am missing a lot of the pieces:

* Code for `App`
* Contents of `'./ssr/lru-cache'`
* `JssProvider`
* `MuiThemeProvider`

If you can't reduce it's complexity, can you share the whole code as a repo so I can replicate it at my end? At this point, I haven't got a clue where to start!

**Comment by revskill10** [comment]
@overlookmotel Please give me some days to reproduce on a minimal repo !

**Comment by overlookmotel** [comment]
Sure. Thank you very much for your effort.

**Comment by overlookmotel** [comment]
By the way, did you mean `react-cache` rather than `reach-cache`?

**Comment by revskill10** [comment]
@overlookmotel Yes, it's `react-cache` .

**Comment by revskill10** [comment]
@overlookmotel I retested with apollo-client and everything works fine. This is a non-issue.

**Comment by overlookmotel** [comment]
@revskill10 OK great. Thanks for letting me know.
