### ISSUE TITLE
[Question] How to catch exception locally?

### ISSUE THREAD

**Issue by DreadBoy** [overlookmotel/react-async-ssr#36]
React doesn't support error boundaries and Suspense when using SSR but since this package allow us to use Suspense in SSR I imagine there would also be a way to write new error boundary. If I understand correctly, each error bubbles up the render tree to nearest Suspense component which checks whether this error is Promise or not. If it isn't Promise, it will rethrow it. 

Do you know of any component/package that would provide such "localised" error boundary and would play nicely with react-async-ssr? Currently we can catch errors in SSR like this:

```ts
try {
  const markup = await renderToStringAsync(<App/>);
}
catch (e) {
  // render 500 page, really bad UX
}
```

I'd like to use error boundaries in SSR, the way we can do it on client.

**Comment by overlookmotel** [comment]
Hi. This is an interesting question you raise.

[react-ssr-error-boundary](https://www.npmjs.com/package/react-ssr-error-boundary) does what you're after. However, it [doesn't support](https://github.com/zekchan/react-ssr-error-boundary/issues/2) the "new" (not really new any more) Context API which was introduced in React 16.3.0. And it also doesn't support Suspense.

It would be possible to add this feature to this package. As you say, Suspense works in a similar way, catching errors that bubble up the component tree to trigger display of alternative content - so a lot of what's needed to make error boundaries work is already implemented in this package.

However, having thought about it, I'm afraid I don't want to add support for this myself. It would likely be time-consuming to code it and write the tests, and I feel there are higher priorities for the core function of this package - notably I'm working on [a package to provide a SSR-enabled version of `React.lazy()`](https://github.com/overlookmotel/react-lazy-ssr) and also want to do the same for lazy-loaded data.

If you want to implement yourself and make a PR, I'd be happy to receive it. However, being realistic, I am crazy busy for next few months and so I won't be able to offer a lot of support/help in doing so. The code is quite well commented though, so maybe it's not so hard to get your head around it.

You up for a bit of a challenge?

**Comment by overlookmotel** [comment]
No answer from OP, so closing.
