### ISSUE TITLE
Broken with React 16.10.0

### ISSUE THREAD

**Issue by revskill10** [overlookmotel/react-async-ssr#40]
I upgrade React to 16.10.0 and my site is broken. It worked with 16.9.0.

There's an issue [here](https://github.com/facebook/react/issues/16938) about this issue.

**Comment by overlookmotel** [comment]
@revskill10 Yes, I saw this last night after they made the release. I'm looking into it.

Can I ask why you closed the issue? Did you find a fix?

**Comment by overlookmotel** [comment]
Related to #39

**Comment by revskill10** [comment]
@overlookmotel I upgraded to React 16.10.1 and every worked fine again. I dont' actually understand why it's broken.

Do you think this library will be usable in future release of React Suspense ?

**Comment by overlookmotel** [comment]
Some things are still broken with React 16.10.1 when using `NO_SSR` option unfortunately. I'm looking into whether it's possible to fix in this package, or whether will require fix/change within React.

My intention is that this package will support all future versions of React. Of course sooner or later React will support SSR of Suspense itself. This package is just a stopgap until then. React's [roadmap](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#an-update-to-the-roadmap) say it's in the works, but does not give a definite timeline.

**Comment by overlookmotel** [comment]
Closing this issue in favour of #39.

**Comment by overlookmotel** [comment]
Turns out React 16.12.0 is producing hydration errors even when not using `No_SSR` option.

Needs fixing or dropping max React version supported to 16.9.x.

**Comment by overlookmotel** [comment]
Decided to drop support for React 16.10.0+ for now.
