### ISSUE TITLE
Problem with Context

### ISSUE THREAD

**Issue by revskill10** [overlookmotel/react-async-ssr#7]
I tried the `constate` library to produce Context.
In Suspense component, i modified the GlobalContext.
In another non-Suspense component (higher level), i use `useContext` to read from global context.
The result is The second component doesn't read the updated Context value which is modified from Suspense component, which results in a mismatched between server and client.
Is this the issue with Context or with this library ?

**Comment by overlookmotel** [comment]
Hi @revskill10.

I'm not familiar with the constate library.

Can you please post a code example and I'll trouble-shoot this. Hooks are a recent addition to React and I've not tested them yet.

**Comment by overlookmotel** [comment]
Please also an you check what version of react-dom you have installed? You'd need to make sure it's >= 16.8.1 for hooks to work.

**Comment by revskill10** [comment]
Hey @overlookmotel , sorry, this is not an issue. It was my mistake for NOT using `setValue` :D 
I tested and it worked with Context nicely.

**Comment by overlookmotel** [comment]
Oh great. Glad you got it sorted.
